In [2]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprice.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [6]:
#changing the na value
import math
median_bedroom=math.floor(df.bedroom.median())
median_bedroom

3

In [8]:
#updating the na value to a median_bedroom value
df.bedroom = df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [9]:
reg = linear_model.LinearRegression()

In [10]:
#area,bedroom & age are independent variables & price is target variable
#independent variables always comes under df[[]]
reg.fit(df[['area','bedroom','age']], df.price)

LinearRegression()

In [12]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [13]:
reg.intercept_

383724.9999999998

In [14]:
reg.predict([[3000,3,40]])

array([444400.])

In [15]:
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [16]:
reg.predict([[2500,4,5]])

array([588625.])